<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NETCHAND-66FR8" failures="1" tests="9" name="UserRestAPITest" time="18.336" errors="0" timestamp="2020-01-24T09:35:53 IST">
  <testcase classname="com.employeeapi.tests.Get_All_Employees" name="checkContentType" time="0.007"/>
  <testcase classname="com.employeeapi.tests.Get_All_Employees" name="checkResponseBody" time="0.029"/>
  <testcase classname="com.employeeapi.tests.Get_All_Employees" name="checkResponseTime" time="0.001"/>
  <testcase classname="com.employeeapi.tests.Get_All_Employees" name="checkStatusCode" time="0.003"/>
  <testcase classname="com.employeeapi.tests.Get_All_Employees" name="checkStatusLine" time="0.002"/>
  <testcase classname="com.employeeapi.tests.GET_Single_Employee_Record" name="checkResponseBody" time="0.001"/>
  <testcase classname="com.employeeapi.tests.Post_User_Record" name="checkResponseBody" time="0.005"/>
  <testcase classname="com.employeeapi.tests.Put_User_Record" name="checkResponseBody" time="0.001"/>
  <testcase classname="com.employeeapi.tests.Delete_user_Record" name="checkResponseBody" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.tests.Delete_user_Record.checkResponseBody(Delete_user_Record.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
</testsuite> <!-- UserRestAPITest -->
